const topics = [
  "Array",
  "String",
  "Hash Table",
  "Dynamic Programming",
  "Math",
  "Sorting",
  "Greedy",
  "Depth-First Search",
  "Database",
  "Binary Search",
  "Breadth-First Search",
  "Tree",
  "Matrix",
  "Bit Manipulation",
  "Two Pointers",
  "Binary Tree",
  "Heap (Priority Queue)",
  "Prefix Sum",
  "Stack",
  "Simulation",
  "Graph",
  "Design",
  "Counting",
  "Sliding Window",
  "Backtracking",
  "Union Find",
  "Linked List",
  "Enumeration",
  "Ordered Set",
  "Monotonic Stack",
  "Trie",
  "Number Theory",
  "Divide and Conquer",
  "Recursion",
  "Bitmask",
  "Queue",
  "Binary Search Tree",
  "Segment Tree",
  "Memoization",
  "Geometry",
  "Hash Function",
  "Binary Indexed Tree",
  "Topological Sort",
  "String Matching",
  "Combinatorics",
  "Rolling Hash",
  "Shortest Path",
  "Game Theory",
  "Interactive",
  "Data Stream",
  "Brainteaser",
  "Monotonic Queue",
  "Randomized",
  "Merge Sort",
  "Iterator",
  "Concurrency",
  "Doubly-Linked List",
  "Probability and Statistics",
  "Quickselect",
  "Bucket Sort",
  "Suffix Array",
  "Minimum Spanning Tree",
  "Counting Sort",
  "Shell",
  "Line Sweep",
  "Reservoir Sampling",
  "Strongly Connected Component",
  "Eulerian Circuit",
  "Radix Sort",
  "Rejection Sampling",
  "Biconnected Component",
];

// Map each topic to an object with 'value' and 'label' properties
const tagoptions = topics.map((topic) => ({ value: topic, label: topic }));

export default tagoptions;
